apiVersion: batch/v1
kind: CronJob
metadata:
  name: tournament-runner
  namespace: gaslight-production
spec:
  schedule: "0 0 * * *"  # Runs daily at midnight
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: tournament-runner
        spec:
          restartPolicy: OnFailure
          automountServiceAccountToken: false
          containers:
            - name: tournament-runner
              image: "rhaversen/gaslight-tournament-runner:${GITHUB_SHA}"
              imagePullPolicy: Always
              resources:
                limits:
                  cpu: "400m"
                  memory: "300M"
                requests:
                  cpu: "250m"
                  memory: "200M"
              envFrom:
                - secretRef:
                    name: tournament-runner-secrets
